### ISSUE TITLE
Error creating Jira issue

### ISSUE THREAD

**Issue by habbdt** [mvelazc0/attack2jira#3]
Hi @mvelazco and Hi @olindoverrillo, 
Thank you for sharing your works. I am trying to implement this for our environment. But while creating the JIRA issue for TTPs I am getting the following error message. Are there any thoughts on how we can resolve this issue. Please let me know if you need any additional information? Thank you for your time. :)

```
[*] Authenticating to https://dev.atlassian.net...
[!] Success!
[*] Creating the Att&ck project...
[!] Success!
[!] Found custom fields
[*] Adding custom fields to ATTACK's default screen tab ...
[!] Done!.
[*] Hiding unnecessary fields from ATTACK's issue layout...
[!] Done.
[*] Obtaining ATT&CK's techniques...
[!] Done!
[*] Creating Jira issues for ATT&CK's techniques...
400
	[!] Error creating Jira issue for T1531
```

**Comment by pjabes** [comment]
Hi @habbdt,

Is this issue still persistent for you?  If so, I believe this may be related to https://github.com/mvelazc0/attack2jira/issues/4 given the 400 in your codeblock.  Could you confirm if you are using Jira Core/Jira Software/Jira Business etc? 

Thanks!

**Comment by mvelazc0** [comment]
@habbdt  is this still an issue for you ?

Thanks

**Comment by mvelazc0** [comment]
@habbdt following up. let us know if this is still an issue. I just tested the whole process and it works. Need to make sure you are using Jira Software, not Jira Cloud.

**Comment by mvelazc0** [comment]
closing this for now. let us know if you see the issue
