### ISSUE TITLE
Unable to create Jira Project

### ISSUE THREAD

**Issue by pjabes** [mvelazc0/attack2jira#4]
Great project!  Appreciate the contribution to the detection eng community. 

I'm  experiencing an issue where a new project is not being created with the initialize argument.  This is on Cloud Jira Core (Free).

```➜  attack2jira git:(master) python3 attack2jira.py -url https://<REDACTED>.atlassian.net -u <REDACTED> -a initialize
Jira API Token for <REDACTED>:
[*] Authenticating to https://<REDACTED>.atlassian.net...
[!] Success!
[*] Creating the Att&ck project...
[!] Error creating Jira project. Does it already exist ?
```

I can confirm that the project does not exist and no existing projects have the "ATTACK" key, nor is a project created after running this script.  

Is this a known issue?

**Comment by pjabes** [comment]
Believe I've found the issue - the schema used to construct the ATTACK project is invalid as per the [Jira API specification](https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-project-get).  Reading through the code comments it seems that it currently uses a deprecated(?) API and invalid arguments, causing a HTTP 400.

```
[*] Authenticating to https://<REDACTED>.atlassian.net...
[!] Success!
[*] Creating the Att&ck project...
----- Debug -----
400
b'{"errorMessages":[],"errors":{"projectType":"An invalid project type was specified. Make sure the project type is available in your Jira instance. Please talk to your Jira administrator if you need more help.","projectKey":"Project \'Mitre Attack Framework\' uses this project key.","projectName":"A project with that name already exists."}}'
----- /Debug -----
[!] Error creating Jira project. Does it already exist ?
``` 

I haven't been able to find much out about the `/rest/simplified/latest/project` API.  Does this project accept code contributions?  Happy to rework the code to utilise the supported API.

**Comment by mvelazc0** [comment]
Thanks for the feedback and raising this Patrick. 

We identified this endpoint by using the UI to create a new project and monitoring the API calls with Chrome developer tools.

It makes sense to move to a proper endpoint and yes, we do accept contributions. Let me know if we can help.

Looking forward to it

**Comment by mvelazc0** [comment]
@pjabes I just tested the initialize function against cloud environment and it worked with no issues. Im not using **Jira Core** though but **Jira Software.**  Can you try that ? 

```
Jira API Token for <REDACTED>:
[*] Authenticating to <REDACTED>...
[!] Success!
[*] Creating the Att&ck project...
[!] Success!
```

**Comment by mvelazc0** [comment]
@pjabes checking in on this. Do you see the issue when using Jira Software ? 

 I have updated the documentation (https://github.com/mvelazc0/attack2jira/commit/6b06008d4620d1a7bd821d025a9003bbd7b836b3) to reflect Jira Software is required to use the tool to avoid confusions.

Thanks

**Comment by pjabes** [comment]
Can confirm that this is indeed a product of the wrong flavor of Jira. I tested both Jira Software Cloud and Jira Core Cloud and can confirm that it works with Jira Software Cloud but not Jira Core Cloud.  This would seem to be due to the missing [Software Development](https://confluence.atlassian.com/confeval/jira-software-evaluator-resources/jira-software-vs-jira-core-license) functionality. 

Annoyingly Jira Software is a [paid product](https://www.atlassian.com/software/jira/core/pricing), which makes it difficult for experimentation and sharing to open source, but I guess that's the price we pay for software.   

But thanks for all of this - much appreciated! Marking as closed.

**Comment by mvelazc0** [comment]
Thanks @pjabes !
You can get a free trial version of Jira Software here. https://www.atlassian.com/software/jira/free
It gives you up to 10 users.  I have been using a trial version for my testing for the past 6 months with no issues.
