### ISSUE TITLE
Unable to Export an ATTACK Navigator JSON layer

### ISSUE THREAD

**Issue by sc00tlad** [mvelazc0/attack2jira#5]
Getting error below when I run the command 
python3 attack2jira.py -url https://yourjiracloud.atlassian.net -u user@domain.com -a export

Traceback (most recent call last):
  File "/opt/attack2jira/lib/jirahandler.py", line 363, in get_technique_maturity
    technique_id=re.search(r"\(([A-Za-z0-9_]+)\)", issue['fields']['summary']).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by mvelazc0** [comment]
Thanks @sc00tlad i was able to replicate the issue. Will spend some time this weekend identifying the source of the problem.

**Comment by mvelazc0** [comment]
@sc00tlad i was able to resolve the issue and just pushed an [update](https://github.com/mvelazc0/attack2jira/commit/5653a3b23b8e442235a9fe075e24c8339a2bffac). Its working for me now. 

```
python attack2jira.py -url https://****.atlassian.net -u *****@gmail.com -a export
Jira API Token for ****@gmail.com:
[*] Authenticating to https://****.atlassian.net...
[!] Success!
[*] Getting issues from the ATTACK project...
[*] Outputting JSON layer attack2jira.json
```
Please pull the latest version and let me know if it works for you now,

Thanks!

**Comment by sc00tlad** [comment]
Worked! thanks!
